version: '3.8'

services:
  api_smart:
    image: chrishubert/whatsapp-web-api:latest
    networks:
      - smartcode
    volumes:
    - api_smart_sessions:/usr/src/app/sessions
    environment:
      - API_KEY=smartcode  
      - BASE_WEBHOOK_URL=https://api2024.smartcode.com.br/
      - ENABLE_LOCAL_CALLBACK_EXAMPLE=TRUE 
      - MAX_ATTACHMENT_SIZE=5000000 
      - SET_MESSAGES_AS_SEEN=TRUE 
     
      - DISABLED_CALLBACKS=message_ack  
      - ENABLE_SWAGGER_ENDPOINT=TRUE 
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 2048M
      labels:
        - traefik.enable=true
        - traefik.http.routers.api_smart.rule=Host(`api2024.smartcode.com.br`)
        - traefik.http.routers.api_smart.entrypoints=websecure
        - traefik.http.routers.api_smart.tls.certresolver=letsencryptresolver
        - traefik.http.routers.api_smart.priority=1
        - traefik.http.routers.api_smart.service=api_smart
        - traefik.http.services.api_smart.loadbalancer.server.port=3000
        - traefik.http.services.api_smart.loadbalancer.passHostHeader=true

volumes:
  api_smart_sessions:
    external: true
    name: api_smart_sessions

networks:
  smartcode:
    name: smartcode
    external: true
